### ISSUE TITLE
Bug Report: get-AzSentinelAlertRule returns playbookName InvalidOperation

### ISSUE THREAD

**Issue by john-joyner** [wortell/AZSentinel#66] opened 2020-04-26 21:41 UTC
# Environment

Windows build number: Microsoft Windows [Version 10.0.18363.778]
PowerShell version (if applicable): PowerShell 7 x64

# Steps to reproduce

install-module -Name AzSentinel
Connect-AzAccount
Set-AzContext -Subscription <SubID> -Tenant <TenantIT>
get-AzSentinelAlertRule -WorkspaceName "<workspace>"

# Expected behavior

Would expect the playbookName field would be populated for rules that have playbooks assigned.

# Actual behavior

playbookName          :

InvalidOperation: C:\Users\<username>\Documents\PowerShell\Modules\AzSentinel\0.6.4\AzSentinel.psm1:506
Line |
 506 |  …             $playbookName = ($playbook.properties.logicAppResourceId) …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | You cannot call a method on a null-valued expression.

**Comment by pkhabazi** [comment] 2020-04-28 07:43
hi @john-joyner can you run the command with -verbose switch and share the output? Also try running the command below:
```
Get-AzSentinelAlertRuleAction -WorkspaceName ""-RuleName ""
```

**Comment by john-joyner** [comment] 2020-04-28 08:34
I tell you what, if I run the command with a rule name specified there is no error and the correct playbookName is returned.

The error only happens when you run with no rule specified, trying to list all the playbooks in one result.

John

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by pkhabazi** [comment] 2020-05-04 08:25
hi @john-joyner I have tested this multiple time and wasn't able to reproduce your error. can you please share your verbose log with me? I hope that we can find the rule that is breaking the function in the verbose output. you can share the output through mail f you don't want to share it here. (remember to remove sub id etc when sharing)
```
Get-AzSentinelAlertRule -WorkspaceName "" -Verbose
````

**Comment by temores** [comment] 2020-06-25 20:45
Hi, 

I found the same issue but only when I tried to export as csv 

Get-AzSentinelAlertRule -WorkspaceName "xxxxxx"  -verbose | Export-Csv .\test.csv

VERBOSE: received 594-byte response of content type application/json
VERBOSE: Content encoding: utf-8
InvalidOperation: E:\OneDrive\Documents\PowerShell\Modules\AzSentinel\0.6.4\AzSentinel.psm1:506
Line |
 506 |  …             $playbookName = ($playbook.properties.logicAppResourceId) …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | You cannot call a method on a null-valued expression.

**Comment by pkhabazi** [comment] 2020-09-03 17:02
hi @temores thanks for your feedback! Can you please share your verbose output. I am not able to reproduce this issue in my own environment. kr, Pouyan

**Comment by pkhabazi** [comment] 2020-10-22 09:15
get-azsentinelalert rule function is updated in version 0.6.12 for better error handling, please test to see if this issue is solved. closing the issue for now.

**Closed by pkhabazi** 2020-10-22 09:15 UTC
Labels: bug
