### ISSUE TITLE
import-azsentinelAlertRule error

### ISSUE THREAD

**Issue by ssi0202** [wortell/AZSentinel#18] opened 2019-10-10 11:57 UTC
This bug tracker is monitored by contributors and the community.

Please use this form and describe your issue, concisely but precisely, with as much detail as possible.
installed ps6 and azsentinel powershell from wotell github. set subscription id and workspace id

Environment

prod

PowerShell version (if applicable):
6

Steps to reproduce

Expected behavior

the rules should be imported to sentinel workspace

i have used the set-Azsentinel to ensure im in the correct azcontext

Actual behavior
input
`PS C:\Users\XXXXX\Downloads\sentinel-attack\detections> Import-AzSentinelAlertRule -WorkspaceName "XXXXXXX" -SettingsFile "sentinel_attack_rules.json"`
result

```
`Import-AzSentinelAlertRule : Unable to connect to APi to get Analytic rules with message: The gateway did not receive a response from 'Microsoft.SecurityInsights' within the specified time period.
At line:1 char:1
+ Import-AzSentinelAlertRule -WorkspaceName "XXXXXXXX" -SettingsFile  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
+ FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Import-AzSentinelAlertRule
`
```

i know this reeks of a permission issue but im stumped

**Comment by pkhabazi** [comment] 2019-10-10 18:17
Thanks for your feedback, set-azsentinel doesn't set your Azure context but enables Azure Sentinel on a existing Log analytics workspace. 

Please check the following:
1. use set-azcontext to switch to the correct subscription or use the -subscription switch to provide the correct subscribtion where you have deployed and enabled Azure Log analytics and Azure sentinel
2. please see if you have permissions to access the log analytics workspace

I have just tested the module again and everything looks good from what I can see.

Please let me know if you need more help with this.

Greetings,
Pouyan

**Comment by pkhabazi** [comment] 2019-10-15 13:08
@ssi0202  please let me know if you need further assist, I am more than happy to help!

**Comment by ssi0202** [comment] 2019-10-15 14:32
hi thanks for the beat back, i have not gotten it to work yet, but i'll try and get my azure "guru" to look at my commands tomorrow. I'm pretty sure it's at my end, just stomped. ;)

**Comment by ssi0202** [comment] 2019-11-01 14:47
ok i fixed it.

i used this instead 
Import-AzSentinelHuntingRule -WorkspaceName "XXXXXXl" -SettingsFile ".\sentinel_attack_rules.json"

so dont use the alert rule to import huntingrules. ;-)

**Comment by pkhabazi** [comment] 2019-11-04 07:30
thanks for the update, so you were using the import-azsentinelalertrule to import hunting rules? I will close this issue, please feel free to open new issue if you have any feedback, suggestion or question.

**Comment by ssi0202** [comment] 2019-11-08 11:20
hi just to clearify 

i was using Import-AzSentinelAlertRule to try and upload the files in the "detections" folder from the sentinel-attack github.

i can get everything running if i used the import-AzsentinelHuntingRule from this folder.

if i try to use the get-AzsentinelAlertRule or import-AzsentinelAlertRule this fails
below is the error when i try to get/list existing alertrules from the sentinel workspace

Get-AzSentinelAlertRule -WorkspaceName "XXXXXX"
Invoke-webrequest : {"error":{"code":"GatewayTimeout","message":"The gateway did not receive a response from 'Microsoft.SecurityInsights' within the specified time period."}}
At C:\Users\ssi.admin\Documents\PowerShell\Modules\AzSentinel\0.6.1\AzSentinel.psm1:365 char:23
+ ... lertRules = Invoke-webrequest -Uri $uri -Method get -Headers $script: ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (Method: GET, Reques\u2026PowerShell/6.2.3
}:HttpRequestMessage) [Invoke-WebRequest], HttpResponseException
+ FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
ConvertFrom-Json : Cannot bind argument to parameter 'InputObject' because it is null.
At C:\Users\ssi.admin\Documents\PowerShell\Modules\AzSentinel\0.6.1\AzSentinel.psm1:366 char:56
+ ... ite-Verbose "Found $((($alertRules.Content | ConvertFrom-Json).value) ...
+                                                  ~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidData: (:) [ConvertFrom-Json], ParameterBindingValidationException
+ FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.ConvertFromJsonCommand


if I use the corresponding command for huntingrules everything works fine, same with importing the sentinel-attack rules as huntingrules. which really puzzels me

**Comment by pkhabazi** [comment] 2019-11-08 13:11
hi @ssi0202  thanks for the update, which version of the AzSentinel module are you using? please try version [0.6.1](https://www.powershellgallery.com/packages/AzSentinel/0.6.1) this one includes some bug fixes.

Can you also share your json file so that we can take a look at it?

**Comment by ssi0202** [comment] 2019-11-11 11:00
hi thanks for getting back to me.

i reimported the azsentinel module below is the version nr


```
Get-Module azsentinel

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     0.6.1      AzSentinel                          {Get-AzSentinelAlertRule, Get-AzSentinelHuntingRule, Get-AzSentinelIncident, Import-AzSentinelAlertRule…}
```


[sentinel_attack_rules - Copy_json.txt](https://github.com/wortell/AZSentinel/files/3830992/sentinel_attack_rules.-.Copy_json.txt)


i had to rename the json file til .txt to get it uploaded here. It's the one here

https://github.com/BlueTeamLabs/sentinel-attack/tree/master/detections

**Comment by ssi0202** [comment] 2019-11-18 19:20
hi, so we do not know what happend, we litteraly tried again today with the exact  same commands and now it works. go ahead and close it. And thanks for making this public/sharing it in the first place

**Comment by pkhabazi** [comment] 2019-12-02 22:47
I am glad to hear that the problem is solved, please feel free to open new issue if you have any questions or feedback! Closing issue as requested

**Closed** 2019-12-02 22:47 UTC
Labels: help wanted, question
